version: "3.9"

x-orbisd: &orbisd
  depends_on: [zanzid]
  tty: true
  stdin_open: true
  image: ko.local/orbisd
  volumes:
    - ../demo:/demo
    - $HOME/.sourcehub:/root/.sourcehub
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  zanzid:
    tty: true
    stdin_open: true
    image: ko.local/zanzid
    volumes:
      - ../demo:/demo
    command: []
    ports:
      - "8080:8080"
      - "8090:8090"

  orbisd1:
    <<: *orbisd
    command: ["start", "--config", "/demo/orbis.1.yaml"]
    ports:
      - "9001:9001"
      - "8081:8081"
      - "8091:8091"

  orbisd2:
    <<: *orbisd
    depends_on: [orbisd1]
    command: ["start", "--config", "/demo/orbis.2.yaml"]
    ports:
      - "9002:9002"
      - "8082:8082"
      - "8092:8092"

  orbisd3:
    <<: *orbisd
    depends_on: [orbisd2]
    command: ["start", "--config", "/demo/orbis.3.yaml"]
    ports:
      - "9003:9003"
      - "8083:8083"
      - "8093:8093"
