version: "3.9"

x-orbisd: &orbisd
  depends_on: [zanzid, sourcehubd]
  tty: true
  stdin_open: true
  image: ko.local/orbisd
  volumes:
    - ../demo:/demo
    - $HOME/.sourcehub:/root/.sourcehub
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-orbisctl: &orbisctl
  depends_on:
    wait-for-orbisd:
      condition: service_completed_successfully
  image: ko.local/orbisd
  volumes:
    - ../demo:/demo

services:
  sourcehubd:
    # profiles: [donotstart]
    tty: true
    stdin_open: true
    image: ko.local/sourcehubd
    volumes:
      - ../demo:/demo
      - $HOME/.sourcehub:/home/nonroot/.sourcehub
    command: ["start", "--log_level", "warn"]
    ports:
      - "26657:26657"
      - "1317:1317"
      - "4500:4500"

  zanzid:
    tty: true
    stdin_open: true
    image: ko.local/zanzid
    volumes:
      - ../demo:/demo
    command: []
    ports:
      - "8080:8080"
      - "8090:8090"

  orbisd1:
    depends_on:
      wait-for-sourcehubd:
        condition: service_completed_successfully
    <<: *orbisd
    command: ["start", "--config", "/demo/orbis.1.yaml"]
    ports:
      - "9001:9001"
      - "8081:8081"
      - "8091:8091"

  orbisd2:
    <<: *orbisd
    depends_on: [orbisd1]
    command: ["start", "--config", "/demo/orbis.2.yaml"]
    ports:
      - "9002:9002"
      - "8082:8082"
      - "8092:8092"

  orbisd3:
    <<: *orbisd
    depends_on: [orbisd2]
    command: ["start", "--config", "/demo/orbis.3.yaml"]
    ports:
      - "9003:9003"
      - "8083:8083"
      - "8093:8093"

  wait-for-sourcehubd:
    image: alpine:3.14
    command: ["sleep", "2"]

  wait-for-orbisd:
    image: alpine:3.14
    command: ["sleep", "5"]

  orbisctl1:
    <<: *orbisctl
    command:
      [
        "-s",
        "orbisd1:8081",
        "ring-service",
        "create-ring",
        "-f",
        "${ORBIS_RING_CONFIG}",
      ]

  orbisctl2:
    <<: *orbisctl
    command:
      [
        "-s",
        "orbisd2:8082",
        "ring-service",
        "create-ring",
        "-f",
        "${ORBIS_RING_CONFIG}",
      ]

  orbisctl3:
    <<: *orbisctl
    command:
      [
        "-s",
        "orbisd3:8083",
        "ring-service",
        "create-ring",
        "-f",
        "${ORBIS_RING_CONFIG}",
      ]
